on:
  workflow_run:
    workflows:
      - .github/workflows/foo.yml
    types:
      - completed

jobs:
  produce:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context, context.repo)

            const temps = ['target']
            const { data: { artifacts } } = await github.rest.actions.listWorkflowRunArtifacts({
              ...context.repo,
              run_id: ${{ github.event.workflow_run.id }},
            })
            console.log(artifacts)

            const artifactsToDelete = artifacts.filter(x => temps.includes(x.name))
            console.log(artifactsToDelete)
            await Promise.all(artifactsToDelete.map(x => {
              github.rest.actions.deleteArtifact({
                ...context.repo,
                artifact_id: x.id,
              })
            }))

