on: [push]

jobs:
  extract-tarball:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        include:
          - os: windows-2016
            host-tag: ltsc2016
          - os: windows-2019
            host-tag: ltsc2019
      fail-fast: false
    steps:
      - run: |
          $dockerfile = @'
            # escape=`
            FROM mcr.microsoft.com/windows/servercore:${{ matrix.host-tag }}
            RUN mkdir bin
            SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]
            RUN $url = 'https://github.com/itzg/rcon-cli/releases/download/1.4.7/rcon-cli_1.4.7_windows_amd64.tar.gz'; `
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; `
              Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile bundle.zip;
            # RUN curl -fsSLo bundle.zip https://github.com/itzg/rcon-cli/releases/download/1.4.7/rcon-cli_1.4.7_windows_amd64.tar.gz
            RUN tar -xvf bundle.zip -C bin
            RUN C:\\bin\rcon-cli.exe --help
            CMD ["C:\\bin\\rcon-cli.exe"]
          '@
          $dockerfile | docker build -t rcon-cli -
          docker run -it --rm rcon-cli --help
