on: [push]

jobs:
  pass-fail-powershell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
      - run: |
          $digest = docker inspect --format='{{index .RepoDigests 0}}' sunghwan2789/minecraft-server:nanoserver-1809
          Write-Host ($null -eq $digest)

  no-fail-powershell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
      - run: docker pull sunghwan2789/minecraft-server:nanoserver-1809
      - run: |
          $digest = docker inspect --format='{{index .RepoDigests 0}}' sunghwan2789/minecraft-server:nanoserver-1809
          Write-Host ($null -ne $digest)
