on: [push]

jobs:
  docker-build-inspect:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t bar .
      - run: docker inspect bar:latest
      - uses: Azure/docker-login@v1
        with:
          username: sunghwan2789
          password: ${{ secrets.DOCKER_PAT }}
  docker-push-inspect:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${{ github.repository }} .
      - run: docker inspect ${{ github.repository }}:latest
      - uses: Azure/docker-login@v1
        with:
          username: sunghwan2789
          password: ${{ secrets.DOCKER_PAT }}
      - run: docker push ${{ github.repository }}
      - run: docker inspect ${{ github.repository }}:latest
