on:
  push:
    branches:
     - main

jobs:
  tool:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

      - run: nuget install Gapotchenko.Eazfuscator.NET -OutputDirectory $env:RUNNER_TEMP
      #- run: dir $env:RUNNER_TEMP -Recurse
      - run: Expand-Archive $env:RUNNER_TEMP\Gapotchenko.Eazfuscator.NET.*\*.nupkg ..\Eazfuscator -PassThru
      - run: gc $env:GITHUB_PATH
      - run: Resolve-Path ..\Eazfuscator\tools
      - run: echo (Resolve-Path ..\Eazfuscator\tools)
      - run: echo (Resolve-Path ..\Eazfuscator\tools) >> $env:GITHUB_PATH 
      - run: Eazfuscator.Net.exe -h
